server:
  port: 8080
app:
  name: "app-server"

spring:
  servlet:
    multipart:
      max-file-size: 6500MB
      max-request-size: 6500MB
  data:
    mongodb:
      uri: mongodb://localhost:27017/quiz

database: "quiz"

ip:
  address: "*"